openapi: 3.1.0
info:
  title: Overseerr API
  description: API for searching and managing media requests in Overseerr.
  version: 1.0.0
servers:
  - url: https://YOUR-OVERSEER-SERVER/api/v1
    description: Local server for Overseerr API
paths:
  /search:
    get:
      operationId: searchMedia
      summary: Search for media by query.
      description: |
        Search for movies or TV shows by query. Queries must be URL-encoded (percent-encoded).  
        Results may include download progress and time estimates for queried content.
      parameters:
        - name: query
          in: query
          required: true
          description: URL-encoded search term for movies or TV shows.
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: Page number for paginated results.
          schema:
            type: integer
        - name: filter
          in: query
          required: false
          description: Optional filter criteria.
          schema:
            type: string
      responses:
        '200':
          description: Search results for media.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        type:
                          type: string
                          enum: [movie, tv]
                        releaseDate:
                          type: string
                          format: date
                        progress:
                          type: object
                          description: Download progress and estimates.
                          properties:
                            percentComplete:
                              type: number
                            estimatedTime:
                              type: string
                              format: duration
  /request:
    post:
      operationId: createRequest
      summary: Create a media request.
      description: Create a new request for movies or TV shows.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mediaType
                - mediaId
                - seasons
              properties:
                mediaType:
                  type: string
                  enum: [movie, tv]
                  description: Type of media to request.
                mediaId:
                  type: integer
                  description: ID of the media item.
                seasons:
                  type: string
                  enum: [all]
                  description: Required for all requests. Defaults to 'all', even for movies.
                is4k:
                  type: boolean
                  description: Set to true for 4K content. Defaults to false.
      responses:
        '201':
          description: Request created successfully.
        '400':
          description: Bad request, invalid input.
        '404':
          description: Media not found.
